### ISSUE TITLE
Bulk delete and update support

### ISSUE THREAD

**Issue by Dimaqa** [netbox-community/pynetbox#316]
In netbox 2.10 REST API Bulk deletion and updation were released.
So i see 2 solutions to implemetnt this:
1. Lazy one: define .delete() .update() functions on Endpoint, which will recieve array of dicts.
2. Implement queryset class similar to django and make response_loader function return it, istead of simple array.
I think thats not really hard either way. 

Whats your thoughts on this?

**Comment by zachmoody** [comment]
Yeah, definitely been leaning towards implementing the second option for a while. Probably a good way to address #270 at the same time.

**Comment by steffenschumacher** [comment]
I'll see if I can manage to add updates also.. disclaimer: flu season has our family down so it might take a while..

**Comment by steffenschumacher** [comment]
Fixed in #404 and #406 ..
