### ISSUE TITLE
Type hints

### ISSUE THREAD

**Issue by Kircheneer** [netbox-community/pynetbox#333]
What is the projects stance on implementing type hints according to [PEP484](https://www.python.org/dev/peps/pep-0484/)?

I would be willing to put in the work if a pull request would be accepted.

**Comment by Kircheneer** [comment]
Just FYI, this is currently not in scope for me personally anymore, it would definitely still be helpful to have.

**Comment by sebastian-philipp** [comment]
I made a pynetbox-stubs package locally:

![pynetbox-stubs](https://user-images.githubusercontent.com/2574405/185944210-591ce600-3225-4a72-8619-35204e31ab1b.gif)

If we end up using this, I can make it available for everyone.

**Comment by sebastian-philipp** [comment]
Ok here you go: https://github.com/sebastian-philipp/pynetbox-stubs . The url is likely to change.

**Comment by arthanson** [comment]
@Kircheneer starting to get this project updated.  If you are interested, please open a PR for this.

**Comment by Kircheneer** [comment]
> @Kircheneer starting to get this project updated. If you are interested, please open a PR for this.

Cool, that's good to hear. As stated above, my focuses have shifted since opening this issue so I will not contribute this in the near future if at all.

**Comment by sebastian-philipp** [comment]
I just moved the repo to https://github.com/interdotlink/pynetbox-stubs

**Comment by abhi1693** [comment]
Since there is no update on this thread, I'm going to close it for now.
