### ISSUE TITLE
Update fails

### ISSUE THREAD

**Issue by wegenerbenjamin** [netbox-community/pynetbox#373]
With the latest version (6.1.2), `update()` calls (as well as `save()` calls) fail. This is most likely due to `pynetbox` retrieving fresh data and overwriting existing data in `pynetbox.core.response.Record.__getattr__()`:
```python
import pynetbox
nb = pynetbox.api('https://netbox.bla.org', token="asdasdasdasdasdasdasdasdasdsadasdsadsdadsasd")
tenant = nb.tenancy.tenants.get(name="T00")
print(tenant.name)
# T00
print(tenant.description)
# 
tenant.description = "BLABLA"
tenant.save()
# False
```

We only checked version 6.0.0 and there no issues occur.

**Comment by markkuleinio** [comment]
I don't know, this is with pynetbox 6.1.2:

```
>>> netbox = pynetbox.api("http://netbox-test.lein.io", token="Xyz")
>>> netbox.version
'2.11'
>>> t = netbox.tenancy.tenants.get(name="Test")
>>> t.name
'Test'
>>> t.description
''
>>> t.description = "testdesc"
>>> t.save()
True
>>> netbox.tenancy.tenants.get(name="Test").description
'testdesc'
>>>
```

Could there be something else that could affect your finding?

**Comment by wegenerbenjamin** [comment]
Thanks for the fast reply. We're on version v2.10.10 (official docker image + ldap) and it's a fresh setup.
We running pynetbox within a setup that has logging enabled and we can see the following HTTP calls when `save()` is called (in this case when updating an IP address):
```
2021-04-21 17:30:17,855 [urllib3.connectionpool][_make_request][DEBUG   ] https://netbox.bla.org:443 "GET /api/ipam/ip-addresses/2/ HTTP/1.1" 200 539
2021-04-21 17:30:17,882 [urllib3.connectionpool][_make_request][DEBUG   ] https://netbox.bla.org:443 "GET /api/tenancy/tenants/2/ HTTP/1.1" 200 388
2021-04-21 17:30:17,908 [urllib3.connectionpool][_make_request][DEBUG   ] https://netbox.bla.org:443 "GET /api/tenancy/tenants/2/ HTTP/1.1" 200 388
```
After switching to pynetbox 6.0.0 it immediatly worked.

**Comment by markkuleinio** [comment]
I don't see how those GET requests relate to the save operation for the tenant, or the ip-addresses operation. In my system (non-docker) I only see a PATCH operation when saving.

**Comment by wegenerbenjamin** [comment]
Calling `save()` for an object will produce the following stack:
```
save()
    self._diff() (L450)
        self.serialize() (L426)
            dict(self)  (L398)   ->  __getattr__()  (L238)          
```
If `self.has_details` is set to `False`, `__getattr__()` will call `self.full_details()` which triggers a GET request and overwrites existing attributes. I'm not quite sure why but it looks like `has_details` is being set to `False`.

**Comment by markkuleinio** [comment]
In my case `.full_details()` is not called in `.__getattr__()`:

https://github.com/netbox-community/pynetbox/blob/ace10614744480b8f8ce7921374936613d17ea68/pynetbox/core/response.py#L248-L249

That is called with `k="keys"` argument so `.full_details()` is not called.

This is with Python 3.7.3 by the way, if that affects this somehow.

**Comment by wegenerbenjamin** [comment]
We're on SLES 15.2 with Python 3.6.13. I will try to produce a full call stack to get proper insights and get back to you.

**Comment by zachmoody** [comment]
:+1:  Curious what you come back with as we do nearly this same process in a couple dozen of our integration tests. Granted not against the tenant endpoint, but I'm not sure what would be special about that one.

**Comment by wegenerbenjamin** [comment]
We checked again and we cannot reproduce the error. I'm sorry for the hassel, I double-checked with a colleague (he reproduced the error) before I opened the ticket. The issue must have been some unknown side-condition.
