### ISSUE TITLE
Iterate Recordset only works once

### ISSUE THREAD

**Issue by mtudury** [netbox-community/pynetbox#374]
Hello,

I have an issue with 6.0.2 and tested too with 6.1.2.

I updated pynetbox from 5.3.1 to 6.0.2 and i found, that the following code stopped working (simplified to demonstrate the issue).

```python
nb = pynetbox.api(
     url=os.environ['IPAM_URL'],
     token=os.environ['IPAM_KEY']
)


print("Load Vrfs")
exist_vrfs = nb.ipam.vrfs.all()

print("iterate pass one")
for ex in exist_vrfs:
  print(ex.name)

print("iterate pass two")
for ex in exist_vrfs:
  print(ex.name)

```

will output :

```
iterate pass one
vrf1
vrf2
...
iterate pass two
```

as a workaround i converted the recordset to list.

thanks,

Matthieu

**Comment by zachmoody** [comment]
Yeah, that's a result of them being generators now. You'll want turn it into a list to be able to iterate on them more than once.

**Comment by mtudury** [comment]
Ah ok, thanks for your reply
