### ISSUE TITLE
.filter() by None not working

### ISSUE THREAD

**Issue by lamoni** [netbox-community/pynetbox#380]
Is there a way to .filter() by None?

Example:
```
site_code = 'blahblah123'
devices = nb.dcim.devices.filter(site=site_code, tenant=None)
```

I would expect this to only return devices in that site that do not have a Tenant set, but I'm seeing it return everything in the site code.

If I add another parameter to filter by, it is respected just like "site" is (as long as it isn't a None):

Example
```
site_code = 'blahblah123'
devices = nb.dcim.devices.filter(site=site_code, tenant=None, manufacturer='juniper')
```

That returns everything in that site code that has a manufacturer of 'juniper', regardless of if there is a tenant set or not

**Comment by markkuleinio** [comment]
Can you try `tenant_id__n="null"` instead of `tenant=None`?

**Comment by markkuleinio** [comment]
FYI, this works for me:

```
>>> all_ip_addresses = netbox.ipam.ip_addresses.all()
>>> len(all_ip_addresses)
2234
>>> ip_addresses = netbox.ipam.ip_addresses.filter(tenant_id="null")
>>> len(ip_addresses)
18
>>>
```

**Comment by raddessi** [comment]
This is a great idea, I would not have thought to do this myself.

**Comment by markkuleinio** [comment]
Yeah, as a reminder to everyone, `pynetbox` does not do ~anything for the `.filter()` arguments, it just sends them as `key=value` URL arguments in the GET request. Great way to learn about these is to use the interactive API browser in the GUI, and there is also a filtering chapter in NetBox documentation: https://netbox.readthedocs.io/en/stable/rest-api/filtering/#lookup-expressions

**Comment by lamoni** [comment]
Thanks @markkuleinio! Closing
