### ISSUE TITLE
Up images for device_types

### ISSUE THREAD

**Issue by nyevess** [netbox-community/pynetbox#384]
Hello,
I'm trying  to up images for device_type using pynetbox.
Do you kwon what kind of file I need for doing this operation?
![image](https://user-images.githubusercontent.com/69692460/122737063-f439af00-d280-11eb-9238-20ab1e6c9ef1.png)
thank you!

**Comment by raddessi** [comment]
I'm not anywhere near an authority on the codebase here but I think from some quick testing and reading through the code in `pynetbox/core/query.py` setting images may not be supported from pynetbox yet. Someone else will have to weigh in to confirm or deny.

**Comment by zachmoody** [comment]
I think that field is read-only and just returns a URL for images that have already been uploaded and associated with the model. You could maybe add the files to wherever they're served from out of the static_assets dir and use the ORM to update that field with their path, but that's just a guess. I vaguely recall S3 objects being supported there too, I'm not sure how it's done though.
