### ISSUE TITLE
Get or filter with custom fields on endpoints regions and locations not working 

### ISSUE THREAD

**Issue by gaussk32** [netbox-community/pynetbox#385]
Netbox v2.11.0
Python 3.8.5
Pynetbox 6.1.2 NOT Working
Pynetbox 6.1.1 NOT Working
Pynetbox 6.1.0 works fine.

1.- Create a custom field integer  or text for regions or locations.
2.- Fill the custom field with an integer or text
3.- with Pynetbox use  get or filter
    nb.dcim.regions.get(cf_cmdesignationid=value)
    nb.dcim.locations.get(cf_cmdesignationid=value)
Expected behavior:

For example with .get it only one element with the requested value on the custom field.

Both methods .get or .filter ignore the asked custom field value and return  all the elements on netbox.
the same kind of get filter with other endpoints like dcim.devices or dcim.sites works fine.

**Comment by markkuleinio** [comment]
Works here with NetBox 2.11.6:

```
>>> pynetbox.__version__
'6.1.2'
>>> regions = netbox.dcim.regions.all()
>>> for region in regions:
...     print(region.name, region.custom_fields)
...
Test {'dhcp_excludes': '321'}
Test2 {'dhcp_excludes': ''}
>>> netbox.dcim.regions.get(cf_dhcp_excludes=321)
Test
>>> netbox.dcim.regions.get(cf_dhcp_excludes=11111)
>>> for region in netbox.dcim.regions.filter(cf_dhcp_excludes="321"):
...     print(region.name, region.custom_fields)
...
Test {'dhcp_excludes': '321'}
>>>
```

**Comment by zachmoody** [comment]
> Both methods .get or .filter ignore the asked custom field value and return all the elements on netbox.
To add, that's usually the default behavior from NetBox when a filter isn't applicable on an endpoint. Can you verify expected behavior with curl?

**Comment by gaussk32** [comment]
On previos versions it works verified
