### ISSUE TITLE
update of object returns true but sometimes clears all data

### ISSUE THREAD

**Issue by Dreetnman** [netbox-community/pynetbox#387]
Hi,

I have encountered an issue when running: interfaceObject.update() 
When calling this function, I get a 'True' return, however sometimes the tagged_vlans remains empty after the update when the list that was provided did contain VLAN objects.
This behaviour is random. Sometimes a devices has no isses, the next time all ports have it and the try after that only one interface has the issue.

This is my code:
```
returnInfo = interfaceObject.update({'label':portName, 'description':interfaceData[1],'mode':mode,'untagged_vlan':untaggedVlan})
```

I tried looping the update command as shown here, without success. It either works the first time or it does not work at all:
```
 returnInfo = interfaceObject.update({'label':portName, 'description':interfaceData[1],'mode':mode,'untagged_vlan':untaggedVlan, 'tagged_vlans':taggedVlanList})

 subcounter = 10
 interfaceObjectCheck = getInterface(nb,key,deviceId)
 untaggedVlanList = interfaceObjectCheck.untagged_vlan
 taggedVlanListtest = interfaceObjectCheck.tagged_vlans

 while len(untaggedVlanList) == 0 or len(taggedVlanListtest) == 0 and subcounter != 0:
     returnInfo = interfaceObject.update({'label':portName, description':interfaceData[1],'mode':mode,'untagged_vlan':untaggedVlan, 'tagged_vlans':taggedVlanList})
     interfaceObjectCheck = getInterface(nb,key,deviceId)
     untaggedVlanList = interfaceObjectCheck.untagged_vlan
     taggedVlanListtest = interfaceObjectCheck.tagged_vlans
     subcounter = subcounter - 1
```

Anyone could help me with this, or has any idea if this is actually a bug?

Thanks in advance!
Best regards,
Dreetnman

**Comment by markkuleinio** [comment]
Hi, can you provide us your `pynetbox` and NetBox versions?

I'm not sure about your code as you are not actually showing anything about the values that you are assigning. And, `untaggedVlanList` doesn't make any sense. `getInterface()` is some of your own functions?

**Comment by Dreetnman** [comment]
Hi,

Pynetbox = v6.1.2
Netbox = v2.11.7

untaggedVlanList = list containing VLAN objects.  The list is filled with code:

**Comment by markkuleinio** [comment]
Thanks, what I recommend is that you test with a simple scenario. The code you presented is actually very complicated and dependent on your previous steps. You haven't shown us any concrete example of the values that you try to assign and how it results. For example (btw entering three backticks indicate start/end of the code block here in the editor):

```
from pprint import pprint
interface = nb.dcim.interfaces.get(...)
pprint(dict(interface))
mode = xxx
untagged_vlan = yyy
tagged_vlans = zzz
print(untagged_vlan)
print(tagged_vlans)
print(interface.update({"mode": mode, "untagged_vlan": untagged_vlan, "tagged_vlans": tagged_vlans}))
interface = nb.dcim.interfaces.get(...)
pprint(dict(interface))
```

**Comment by Dreetnman** [comment]
Hi,

While implementing this code in my project, to make it easier to troubleshoot. it looks like there was an issue with the compiler / garbage collection. In short, after printing the objects first, there is no issue ...

I will close this as for now it does not look like it is a issue of pynetbox.

Thanks for the quick responses!

Best regards,
