### ISSUE TITLE
Support get()/all()/filter() to return model class instead of Record class

### ISSUE THREAD

**Issue by lordofire** [netbox-community/pynetbox#392]
When we do certain resource type get()/all()/filter() operations, the returned objects have class of Record. However, under the situation that each of the above methods are read under certain endpoint, it looks pretty straightforward to return the class defined in the model instead of base class Record. Also, I saw there is a way to pass in `model` [here](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L55), but seems not used.

**Comment by steffenschumacher** [comment]
I guess this would need someone to create all the models used in NB, and keep these up to date all the time?
Also you wouldn't have the custom fields, since these would all be depending on each install - I think it might be better to somehow read the openapi spec + somehow get custom fields and have a script compile/generate the model classes which could be loaded and used if the name matches - but this is a huge effort I think?

**Comment by zachmoody** [comment]
Yeah, the approach I went with for pynetbox in the beginning was to have `Record` cover as many use-cases as was reasonable without adding a ton of conditionals for outliers that were a little different from the majority. Those exceptions were addressed with models. I wanted to limit the number we had to write. Using the openapi spec's been brought up before, but there's been a few times it hasn't accurately represented the API. That was a long time ago though, I don't know if it's any better.

**Comment by johanfleury** [comment]
@zachmoody I was looking at a way to use external models and I think I came up with something that could fix this issue, but it uses a “global variable”, which you might not like:

```diff
diff --git a/pynetbox/__init__.py b/pynetbox/__init__.py
index 0e1f510..abbbf04 100644
--- a/pynetbox/__init__.py
+++ b/pynetbox/__init__.py
@@ -2,6 +2,7 @@ from pkg_resources import get_distribution, DistributionNotFound

 from pynetbox.core.query import RequestError, AllocationError, ContentError
 from pynetbox.core.api import Api as api
+from pynetbox.core.app import register_model

 try:
     __version__ = get_distribution(__name__).version
diff --git a/pynetbox/core/app.py b/pynetbox/core/app.py
index 797eb17..9991c06 100644
--- a/pynetbox/core/app.py
+++ b/pynetbox/core/app.py
@@ -25,6 +25,16 @@ from pynetbox.models import (
     wireless,
 )

+MODELS = {
+    "dcim": dcim,
+    "ipam": ipam,
+    "circuits": circuits,
+    "virtualization": virtualization,
+    "extras": extras,
+    "users": users,
+    "wireless": wireless,
+}
+

 class App(object):
     """ Represents apps in NetBox.
@@ -40,32 +50,18 @@ class App(object):
         self.api = api
         self.name = name
         self._choices = None
-        self._setmodel()
-
-    models = {
-        "dcim": dcim,
-        "ipam": ipam,
-        "circuits": circuits,
-        "virtualization": virtualization,
-        "extras": extras,
-        "users": users,
-        "wireless": wireless,
-    }
-
-    def _setmodel(self):
-        self.model = App.models[self.name] if self.name in App.models else None

     def __getstate__(self):
         return {"api": self.api, "name": self.name, "_choices": self._choices}

     def __setstate__(self, d):
         self.__dict__.update(d)
-        self._setmodel()

     def __getattr__(self, name):
         if name == "secrets":
             self._set_session_key()
-        return Endpoint(self.api, self, name, model=self.model)
+        return Endpoint(self.api, self, name, model=MODELS.get(self.name, None))

     def _set_session_key(self):
         if getattr(self.api, "session_key"):
@@ -194,3 +190,7 @@ class PluginsApp(object):
             http_session=self.api.http_session,
         ).get()
         return installed_plugins
+
+
+def register_model(name, model):
+    MODELS[name] = model
```

To give more context: I’m working with the netbox-dns plugin and I thought I could simply overload the `App._setmodel()` method to make pynetbox use my models, but I figured a new `App` instance is created in [the `Record._endpoint_from_url` method](https://github.com/netbox-community/pynetbox/blob/7e98109a982274a1007c8f56c1ca6a60f631b52b/pynetbox/core/response.py#L393] which prevent me from doing this.

With the above diff, I can now write something like this:

```python
# cli.py
import pynetbox

from . import models


def main():
    pynetbox.register_model("plugins/netbox-dns", models)

    nb = pynetbox.api(...)

    for zone in nb.plugins.netbox_dns.zones.all():
        for rr in zone.records.list():
                ...

# models.py
from pynetbox.core.response import Record
from pynetbox.core.endpoint import RODetailEndpoint


class Zones(Record):
    @property
    def records(self):
        return RODetailEndpoint(self, "records", Record)
```

What do you think?

**Comment by zachmoody** [comment]
I don't think I mind the global, but I have a feeling tinkering with `__setstate__` is going mess with pickling. Are the tests ok after that change?

**Comment by markkuleinio** [comment]
I'm confused: Why is `models` named "models" even though it is all about apps? I'm not Django-fluent so I may have misunderstood something 😄

Anyway, this `register_model()` approach seems interesting. I mean, if someone is writing code where it is (for some project-internal reason or due to using specific plugins) essential to deal with distinct models instead of generic `Record`s, this makes it possible, right? `pynetbox` can then concentrate on having the custom models only for the cases where the specific properties/fields are absolutely needed with the base NetBox (the child endpoints and JSON fields etc.).

(`MODELS` replaced with `_APPS` I'd say)

**Comment by markkuleinio** [comment]
Btw about OpenAPI:

> Using the openapi spec's been brought up before

In NetBox 3.0.5 an internal cache was added in https://github.com/netbox-community/netbox/commit/257c0afdb5b62c7ea84159d2b46d53ce5a43f3a3 so now only the first `/api/docs/?format=openapi` call is very slow (several seconds) and then subsequent calls within 24 hours are fast. It's very awkward if `pynetbox` starts using the OpenAPI spec and it leads to sporadic freezes in the applications or delays in starting the applications.

**Comment by johanfleury** [comment]
@zachmoody 
> Are the tests ok after that change?

Tests in `test/integration/` fail to pass locally (I had the same issue when working on #426), but all the unit tests work as is.

I’ve created #433 for you to review and run the GH workflows.

---

@markkuleinio 
> I'm confused: Why is models named "models" even though it is all about apps? I'm not Django-fluent so I may have misunderstood something smile
> […]
> (`MODELS` replaced with `_APPS` I'd say)

This is the name currently used in pynetbox, I kept it as is for consistency but I also had to wrap my head around what a model was.

> Anyway, this register_model() approach seems interesting. I mean, if someone is writing code where it is (for some project-internal reason or due to using specific plugins) essential to deal with distinct models instead of generic Records, this makes it possible, right?

Yes. One just need to create classes in a module and pass that module to `register_models()`

**Comment by lordofire** [comment]
@zachmoody Agreed on your justification on this. Since the `Record` class has url, we could use that to distinguish the object type. Thanks all for taking a look at this.
