### ISSUE TITLE
How to mimic get or create behaviour?

### ISSUE THREAD

**Issue by surfer190** [netbox-community/pynetbox#393]
Good day, I have noticed that the `get` method does not allow for multiple fields.

The problem is when using `get_or_create` setup - I stuggle to get it to work.

I want to check if an interface exists linked to a specific device, unfortunately you cannot use multiple fields with `get`.
So I try to use `filter` but the result of that evaluates to False.

```
ipdb> intf = nb.dcim.interfaces.get(device=1, name='bond0')
ipdb> intf
ipdb> intf = nb.dcim.interfaces.get(name='bond0')
ipdb> intf
bond0
ipdb> intf.device.id
1
ipdb> intfs = nb.dcim.interfaces.filter(device=1, name='bond0')
ipdb> intfs
<pynetbox.core.response.RecordSet object at 0x10bd46f70>
ipdb> intfs == True
False
```

Here is an example of creating an interface with the same name on another device:

```
intf2 = nb.dcim.interfaces.create(device=2, name='bond0', type='virtual')
```

How can I check that a specific interface linked to a specific device exists before creating another one?

**Comment by markkuleinio** [comment]
Use `device_id` argument instead of `device`.
