### ISSUE TITLE
Get an ip address from the global vrf

### ISSUE THREAD

**Issue by surfer190** [netbox-community/pynetbox#400]
I am using the `get` method to acquire a single record:

pynetbox get an ip from the global vrf:

    vrf_id = None
    ip = nb.ipam.ip_addresses.get(   
        address='172.17.0.1/32',
        vrf_id=vrf_id
    )

Unfortunately this results in a value error, when there are instances of this ip in different vrfs in the database. How can I ensure I get only the single instance?

`*** ValueError: get() returned more than one result. Check that the kwarg(s) passed are valid for this endpoint or use filter() or all() instead`

**Comment by surfer190** [comment]
@markkuleinio any ideas?

**Comment by markkuleinio** [comment]
Did you try

```
nb.ipam.ip_addresses.get(address="172.17.0.1/32", vrf="null")
```
(or `vrf_id="null"`)

(`pynetbox` does not really handle any of the arguments, it just sends them as URL parameters and `null` might be the correct match in NetBox API call)
