### ISSUE TITLE
Make verify ssl optional via requests

### ISSUE THREAD

**Issue by codekuu** [netbox-community/pynetbox#403]
A lot of people including me are using development servers which has self signed or no certificate installed for the dev domain.
Would need the verification process of the certificate via requests to be optional.

**Comment by codekuu** [comment]
Solution can be found in the added commit.

**Comment by markkuleinio** [comment]
See also https://github.com/netbox-community/pynetbox/releases/tag/v5.0.0

**Comment by codekuu** [comment]
Thank you. I am guessing you removed the ssl_verify for a reason so I'll close this issue and continue to implement it by `x.http_session.verify = False` instead
