### ISSUE TITLE
Pynetbox 6.1.3 and Netbox 3.03

### ISSUE THREAD

**Issue by prestigio391** [netbox-community/pynetbox#408]
Hello,

Iam trying POST new device to netbox with pynetbox...Getters are OK.>also in postman working..

import pynetbox
import logging

#from pynetbox.core.endpoint import response_loader
#rom pynetbox.models.dcim import DeviceTypes
dev = "TEST_PYTHON_RT"
def adddev(dev):
    nb = pynetbox.api(url='https://127.0.0.1/',
                  token='ce010b623087a43e3bf6aacf4b10ad2694084533')
    nb.http_session.verify = False

    result = nb.dcim.devices.create(
        name=dev,
        device_type=2,
        device_role=1,
        site=1,
    )

    print(result)

But without succss..script without errors but device isnt added to netbox...how i can debug communication between pynetbox and netbox please ?

**Comment by jamieparks** [comment]
I also have this issue, pointing the exact same code at an older version (2.6.9) works fine, but fails to create new objects on 3.0.3 without a warning. 

`
import pynetbox
nb_server = 'http://x.x.x.x'
nb_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

netbox = pynetbox.api(
        url=nb_server,
        token=nb_token
        )

netbox.http_session.verify = False


try:
    netbox.dcim.manufacturers.create(name="test",slug="test")
except pynetbox.RequestError as e:
    print("Error: {}".format(str(e)))


`

**Comment by japa85** [comment]
sorted the issue, calling http not https

**Comment by prestigio391** [comment]
> Hello,
> 
> Iam trying POST new device to netbox with pynetbox...Getters are OK.>also in postman working..
> 
> import pynetbox import logging
> 
> #from pynetbox.core.endpoint import response_loader #rom pynetbox.models.dcim import DeviceTypes dev = "TEST_PYTHON_RT" def adddev(dev): nb = pynetbox.api(url='https://127.0.0.1/', token='ce010b623087a43e3bf6aacf4b10ad2694084533') nb.http_session.verify = False
> 
> ```
> result = nb.dcim.devices.create(
>     name=dev,
>     device_type=2,
>     device_role=1,
>     site=1,
> )
> 
> print(result)
> ```
> 
> But without succss..script without errors but device isnt added to netbox...how i can debug communication between pynetbox and netbox please ?

**Comment by prestigio391** [comment]
> Hello,
> 
> Iam trying POST new device to netbox with pynetbox...Getters are OK.>also in postman working..
> 
> import pynetbox import logging
> 
> #from pynetbox.core.endpoint import response_loader #rom pynetbox.models.dcim import DeviceTypes dev = "TEST_PYTHON_RT" def adddev(dev): nb = pynetbox.api(url='https://127.0.0.1/', token='ce010b623087a43e3bf6aacf4b10ad2694084533') nb.http_session.verify = False
> 
> ```
> result = nb.dcim.devices.create(
>     name=dev,
>     device_type=2,
>     device_role=1,
>     site=1,
> )
> 
> print(result)
> ```
> 
> But without succss..script without errors but device isnt added to netbox...how i can debug communication between pynetbox and netbox please ?

**Comment by prestigio391** [comment]
Ok mu
