### ISSUE TITLE
pynetbox.readthedocs.io is not updated to 6.2.0, still at 6.1.3

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/pynetbox#414]
See https://pynetbox.readthedocs.io/en/latest/endpoint.html and compare it to https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py

Something (whetever triggers the update) has apparently not generated new documentation in readthedocs because in browser the title bar still says "**Endpoint - pynetbox 6.1.3 documentation**"

**Comment by markkuleinio** [comment]
Updated now with the pynetbox 6.3.0 release, thanks @zachmoody!

**Comment by markkuleinio** [comment]
Actually now that I see the documentation with a desktop browser, it says "**pynetbox 6.2.1.dev19+gc702fd1**" so some update process may still need fixing.

**Comment by zachmoody** [comment]
I'm not sure what's going on with it. Seems to only do that on the latest version of the docs. Stable seems right. Nothing in RTD indicates a problem with recent releases. :man_shrugging:

**Comment by markkuleinio** [comment]
Looks fine now with 6.4.0.
