### ISSUE TITLE
The `ipaddresses` of a Service return IP elements with an empty representation

### ISSUE THREAD

**Issue by alexbarcelo** [netbox-community/pynetbox#417]
```python
services = list(nb.ipam.services.filter(tag="node-exporter")
print(svc.ipaddresses)
# []
# prints an empty list
```

The list itself is not empty, but the `Record` object has an empty representation (which is very confusing and I was troubleshooting a completely bogus problem).

As of right now, I am using last version of pynetbox (6.2.0) and last version of NetBox (3.0.11). I noticed this "blank representation" bug with NetBox v3.0.2 and just upgraded, and I keep seeing this same behavior.

**Comment by alexbarcelo** [comment]
Probably is obvious for somebody that understands the internals, but it was a surprise for me, and maybe it is relevant:

```
In [3]: services = nb.ipam.services.get(id=1)

In [4]: services["ipaddresses"][0]
Out[4]: 
{'id': 98,
 'url': 'http://172.21.128.34/api/ipam/ip-addresses/98/',
 'display': '2100::42/64',
 'family': 6,
 'address': '2100::42/64'}

In [5]: services.ipaddresses
Out[5]: []

In [6]: services["ipaddresses"][0]
Out[6]: 
{'id': 98,
 'url': 'http://172.21.128.34/api/ipam/ip-addresses/98/',
 'display': '2100::42/64',
 'family': {'value': 6, 'label': 'IPv6'},
 'address': '2100::42/64',
 'vrf': None,
 'tenant': None,
 'status': {'value': 'active', 'label': 'Active'},
 'role': None,
 'assigned_object_type': 'virtualization.vminterface',
 'assigned_object_id': 10,
 'assigned_object': {'id': 10,
  'url': 'http://172.21.128.34/api/virtualization/interfaces/10/',
  'display': 'eth0',
  'virtual_machine': {'id': 13,
   'url': 'http://172.21.128.34/api/virtualization/virtual-machines/13/',
   'display': 'ridley',
   'name': 'ridley'},
  'name': 'eth0'},
 'nat_inside': None,
 'nat_outside': None,
 'dns_name': 'ridley.betarho.lan',
 'description': '',
 'tags': [{'id': 10,
   'url': 'http://172.21.128.34/api/extras/tags/10/',
   'display': 'autogenerated',
   'name': 'autogenerated',
   'slug': 'autogenerated',
   'color': '9e9e9e'}],
 'custom_fields': {},
 'created': '2021-11-29',
 'last_updated': '2021-11-29T19:21:59.586016Z'}
```

**Comment by markkuleinio** [comment]
Let's just say that there are already pull requests pending that address exactly this kind of situations 😉

(Seriously though: the returned objects don't apparently have `name` attribute and thus the default string representation of the object is just blank, which is confusing but going to be addressed in the near future if you sit tight)

**Comment by alexbarcelo** [comment]
Ok, now that I know what is happening (at the beginning I completely misunderstood the problem and thought that the list was empty :confused: ) I see that #388, #389 and #390 are related to this. A mechanism to fix the issues there should also fix this empty ip representation. (Although the attributes that `user` would use for representation are not the same that `ipaddress` would use, but that should be straightforward to extend).

I'll sit tight; as it is now, it confuses the user while using the interactive interpreter or log messages, but the application flow works cleanly, so I am not really worried.

**Comment by markkuleinio** [comment]
Yeah, as a general rule I only use the default (`str()`) representation of the object when testing things interactively, but in the application code I always specifically use and output whatever attribute is the most suitable one for the object, like `device.name`, `ipaddress.address`, `prefix.prefix` etc., often with list comprehension like `tag_names = [tag.name for tag in device.tags]`.
