### ISSUE TITLE
Add support for `/api/ipam/vlan-groups/nnn/available-vlans/` child endpoint

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/pynetbox#427]
In https://github.com/netbox-community/netbox/commit/e0cfd5e49bda860353702affd435f62bf9322dd4 for **NetBox 3.2** (still a `feature` branch) there is a child endpoint for allocating next available VLAN ID in a VLAN group. This requires additional code in `pynetbox` as well.

**Comment by jeremystretch** [comment]
FYI the relevant NetBox FR for this addition is [here](https://github.com/netbox-community/netbox/issues/2658). Let me know if I can be of any help!

**Comment by markkuleinio** [comment]
Thanks @jeremystretch, I'm currently testing my code and I see that the list items for `available-vlans` do not correspond to any current `pynetbox` models, so I think I need to create a new model for this. The plain `Record` does not seem fit because the returned data does not have the `display` field so there is no `str` output:

```
>>> netbox.version
'3.2'
>>> vg = netbox.ipam.vlan_groups.get(name="TestGroup")
>>> vg.min_vid, vg.max_vid
(10, 12)
>>> vg.available_vlans.list()
[, , ]
# Three "empty" items as there is no `name`, `label` or `display` attribute
>>> v = vg.available_vlans.list()[0]
>>> type(v)
<class 'pynetbox.core.response.Record'>
>>> ppr(dict(v))
{'group': {'display': 'TestGroup',
           'id': 1,
           'name': 'TestGroup',
           'slug': 'testgroup',
           'url': 'http://netbox-future.lein.io/api/ipam/vlan-groups/1/'},
 'vid': 10}
>>>
```

So I can create a new `AvailableVlans(Record)` class for this and use `str(self.vid)` for string representation.

Or, do you think it would be useful to have a `display` field in the `available-vlans` results in NetBox?

I'll create a PR here for this in a moment anyway.
