### ISSUE TITLE
snapshot() function

### ISSUE THREAD

**Issue by PieterL75** [netbox-community/pynetbox#429]
the Netbox API has the 'snapshot()' function
This will take a snapshot of the object, and when saved, the difference will be logged.

I don't see this implemented in pynetbox. Can this be added ?

ty!

Pieter

**Comment by markkuleinio** [comment]
Can you tell more about this snapshot feature, like a documentation link or API path?

**Comment by jeremystretch** [comment]
`snapshot()` is an internal method on the Python model. It's called automatically as necessary to effect change logging (aside from the case documented in bug #6389). It's not something that can be exposed remotely, not should it need to be. What are you trying to accomplish?

**Comment by PieterL75** [comment]
When using the custom scripts, i have to call the snapshot function before checking an object. Otherwise the save() does not store the diff.

But I found in the meantime that through pynetbox, the diff is there after an update.

So all good, nothing required to be changed!

Peter
