### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/pynetbox#431]
[6.0.0 release notes](https://github.com/netbox-community/pynetbox/releases/tag/v6.0.0) say: "Ends python 2 support." However the code still has `six` and other Python 2 fixes.

Maybe drop the Python 2 compatibility code for real in `pynetbox` 7.0.0?

I can do a PR for this if needed.

**Comment by zachmoody** [comment]
Yeah, I think in practice, that meant we stopped testing against py2. Keeping it around doesn't bother me too much, but we can drop it in the next major release.

**Comment by markkuleinio** [comment]
I will submit the PR for this after NetBox 3.2 beta has come out, then we know if something else should be added in `pynetbox` major release. Based on release history and recent developments I guess the beta will be out in a month or two.

NetBox 3.2 will require Python 3.8 or newer, so users deploying it should be quite used to modern Python.
