### ISSUE TITLE
Have options to get()/filter() of an endpoint to return objects with full_details()

### ISSUE THREAD

**Issue by lordofire** [netbox-community/pynetbox#435]
Can anyone point to me if it is feasible to directly pull the full details objects by regular get/filter in the netbox endpoints? Issuing `.full_details()` one at a time after filter() is painful in the performance perspective. Any help or comment is welcomed. Thanks!

**Comment by markkuleinio** [comment]
Can you tell more about your problem?

```
>>> ip = netbox.ipam.ip_addresses.get(1)
>>> ppr(dict(ip))
{'address': '1.1.1.1/32',
 'assigned_object': None,
 'assigned_object_id': None,
 'assigned_object_type': None,
 'created': '2022-01-05',
 'custom_fields': {},
 'description': '',
 'display': '1.1.1.1/32',
 'dns_name': '',
 'family': {'label': 'IPv4', 'value': 4},
 'id': 1,
 'last_updated': '2022-01-06T11:46:30.441218+02:00',
 'nat_inside': None,
 'nat_outside': None,
 'role': None,
 'status': {'label': 'Active', 'value': 'active'},
 'tags': [{'color': '9e9e9e',
           'display': 'TestTag1',
           'id': 1,
           'name': 'TestTag1',
           'slug': 'testtag1',
           'url': 'http://netbox-future.lein.io/api/extras/tags/1/'}],
 'tenant': None,
 'url': 'http://netbox-future.lein.io/api/ipam/ip-addresses/1/',
 'vrf': None}
>>> ip.full_details()
True
>>> ppr(dict(ip))
{'address': '1.1.1.1/32',
 'assigned_object': None,
 'assigned_object_id': None,
 'assigned_object_type': None,
 'created': '2022-01-05',
 'custom_fields': {},
 'description': '',
 'display': '1.1.1.1/32',
 'dns_name': '',
 'family': {'label': 'IPv4', 'value': 4},
 'id': 1,
 'last_updated': '2022-01-06T11:46:30.441218+02:00',
 'nat_inside': None,
 'nat_outside': None,
 'role': None,
 'status': {'label': 'Active', 'value': 'active'},
 'tags': [{'color': '9e9e9e',
           'display': 'TestTag1',
           'id': 1,
           'name': 'TestTag1',
           'slug': 'testtag1',
           'url': 'http://netbox-future.lein.io/api/extras/tags/1/'}],
 'tenant': None,
 'url': 'http://netbox-future.lein.io/api/ipam/ip-addresses/1/',
 'vrf': None}
>>>

>>> ip = netbox.ipam.ip_addresses.get(address="1.1.1.1/32", brief=1)
>>> ppr(dict(ip))
{'address': '1.1.1.1/32',
 'display': '1.1.1.1/32',
 'family': 4,
 'id': 1,
 'url': 'http://netbox-future.lein.io/api/ipam/ip-addresses/1/'}
>>>
```

**Comment by markkuleinio** [comment]
Same object contents with `.filter()`:

```
>>> ip = next(netbox.ipam.ip_addresses.filter(address="1.1.1.1"))
>>> pprint(dict(ip))
{'address': '1.1.1.1/32',
 'assigned_object': None,
 'assigned_object_id': None,
 'assigned_object_type': None,
 'created': '2022-01-05',
 'custom_fields': {},
 'description': '',
 'display': '1.1.1.1/32',
 'dns_name': '',
 'family': {'label': 'IPv4', 'value': 4},
 'id': 1,
 'last_updated': '2022-01-06T11:46:30.441218+02:00',
 'nat_inside': None,
 'nat_outside': None,
 'role': None,
 'status': {'label': 'Active', 'value': 'active'},
 'tags': [{'color': '9e9e9e',
           'display': 'TestTag1',
           'id': 1,
           'name': 'TestTag1',
           'slug': 'testtag1',
           'url': 'http://netbox-future.lein.io/api/extras/tags/1/'}],
 'tenant': None,
 'url': 'http://netbox-future.lein.io/api/ipam/ip-addresses/1/',
 'vrf': None}
>>>
```

**Comment by lordofire** [comment]
> Same object contents with `.filter()`:
> 
> ```
> >>> ip = next(netbox.ipam.ip_addresses.filter(address="1.1.1.1"))
> >>> pprint(dict(ip))
> {'address': '1.1.1.1/32',
>  'assigned_object': None,
>  'assigned_object_id': None,
>  'assigned_object_type': None,
>  'created': '2022-01-05',
>  'custom_fields': {},
>  'description': '',
>  'display': '1.1.1.1/32',
>  'dns_name': '',
>  'family': {'label': 'IPv4', 'value': 4},
>  'id': 1,
>  'last_updated': '2022-01-06T11:46:30.441218+02:00',
>  'nat_inside': None,
>  'nat_outside': None,
>  'role': None,
>  'status': {'label': 'Active', 'value': 'active'},
>  'tags': [{'color': '9e9e9e',
>            'display': 'TestTag1',
>            'id': 1,
>            'name': 'TestTag1',
>            'slug': 'testtag1',
>            'url': 'http://netbox-future.lein.io/api/extras/tags/1/'}],
>  'tenant': None,
>  'url': 'http://netbox-future.lein.io/api/ipam/ip-addresses/1/',
>  'vrf': None}
> >>>
> ```

Hi Mark,

Thanks for your feedback. Seems like the issues I'm encountering is more on the virtual machine object side, like the following:
```
{'cluster': {'display': 'cluster1',
             'id': 53,
             'name': 'cluster1',
             'url': 'https://netbox.prod:30443/api/virtualization/clusters/53/'},
 'comments': '',
 'config_context': {},
 'created': '2021-12-16',
 'custom_fields': {},
 'disk': 50,
 'display': 'test-vm',
 'id': 721,
 'last_updated': '2021-12-16T12:07:44.829831Z',
 'local_context_data': None,
 'memory': 7961,
 'name': 'test-vm',
 'platform': None,
 'primary_ip': {'address': '10.100.10.120/24',
                'display': '10.100.10.120/24',
                'family': 4,
                'id': 36243,
                'url': 'https://netbox.prod:30443/api/ipam/ip-addresses/36243/'},
 'primary_ip4': {'address': '10.100.10.120/24',
                 'display': '10.100.10.120/24',
                 'family': 4,
                 'id': 36243,
                 'url': 'https://netbox.prod:30443/api/ipam/ip-addresses/36243/'},
 'primary_ip6': None,
 'role': None,
 'site': {'display': 'region1',
          'id': 25,
          'name': 'region1',
          'slug': 'region1',
          'url': 'https://netbox.prod:30443/api/dcim/sites/25/'},
 'status': {'label': 'Active', 'value': 'active'},
 'tags': [],
 'tenant': None,
 'url': 'https://netbox.prod:30443/api/virtualization/virtual-machines/721/',
 'vcpus': 4.0}
```
And the field I'm trying to access is `cluster.type`, where it is not shown in the above cluster object return value either. Double-checked the netbox REST API document, and seems like it does not contain type information for the default cluster object return value. Is there anyway we could pull this together with filter() api call, so that I could save per object api call? I think probably GraphQL interface could help on that, but just want to double check if it is applicable on the REST part. Thanks!

**Comment by markkuleinio** [comment]
I'd say it is not possible to command the NetBox REST API to gather additional information in the results. I would just fetch all the clusters first in the application (to get the types and whatnot), and then find the types from there while doing the VM filtering.

If you feel that the `cluster` data should contain the type as well, you can try raising a feature request in NetBox. I haven't used GraphQL so I don't know if it handles the need efficiently.

**Comment by zachmoody** [comment]
Unless I'm missing something. The time involved with calling `.full_details()` is almost entirely due to the request to the "detail" endpoint. Moving that behind the scenes isn't going to make the process any more performant. It might even be less so since we may end up making calls for objects you didn't care about. Imo, this is exactly what the graphql api is best at.

**Comment by lordofire** [comment]
Thanks for your suggestions! Closing this issue now.
