### ISSUE TITLE
Adding recent NetBox versions in integration tests

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/pynetbox#438]
The integration tests implemented last year in `pynetbox` only test against NetBox 2.7, 2.8, 2.9 and 2.10. Currently the three latest NetBox releases are 2.11, 3.0 and 3.1.

Would @raddessi or someone else be willing to update the integration tests for recent NetBox versions? Or was there some intention to rewrite the tests somehow else?

Btw I had a quick Twitter poll in December about the NetBox versions that people mostly use 😊

![image](https://user-images.githubusercontent.com/25136274/150629889-676e6a82-0b03-4b22-a17f-0be401ffedaa.png)

**Comment by raddessi** [comment]
Oh for sure, im pretty backlogged atm but I will try to get to it. Thanks for the heads up, im sorry i have not had much time to check on this project recently.

**Comment by raddessi** [comment]
Feel free to assign me for now.

**Comment by raddessi** [comment]
Should be good to go :) Thanks for the mention.

I would like to really update the test suite to use [nox](https://github.com/theacodes/nox) which should help make running individual sessions more user friendly, and then overhaul the docker logic to clean that up as well. I'm trying to get a currently-private `netbox-load-balancing` project approved to be open-sourced, once that is opened up I'll ask you both to look over how that one works and if you like it I may update this project similarly.

If I can help with anything else in the meantime just let me know.
