### ISSUE TITLE
Bulk deletion on pynetbox

### ISSUE THREAD

**Issue by tars01** [netbox-community/pynetbox#443]
For the below new bulk deletion feature on the API, how do we replicate this functionality on pynetbox?

https://github.com/netbox-community/netbox/pull/5455
REST API Bulk Deletion (https://github.com/netbox-community/netbox/issues/3436)

Thanks

**Comment by markkuleinio** [comment]
https://pynetbox.readthedocs.io/en/latest/endpoint.html#pynetbox.core.endpoint.Endpoint.delete ?

**Comment by tars01** [comment]
> https://pynetbox.readthedocs.io/en/latest/endpoint.html#pynetbox.core.endpoint.Endpoint.delete ?

Thank you, perfect. I realised I needed to upgrade pynetbox which was why it didn't work for me.
