### ISSUE TITLE
Vlans __str__ function creates TypeError

### ISSUE THREAD

**Issue by qwertiko** [netbox-community/pynetbox#447]
Since commit 86ef8093c5a49eca4a29f8655cfc39c42c258ca6 the \_\_str__ function of a vlan object doesn´t work anymore.
This makes a simple call like this unable to complete

> import pynetbox
> NBS = pynetbox.api('https://xxx.xx', token='xxxx')
> for x in NBS.ipam.vlans.all():
> print(x)

with the following error:
`TypeError: Record.__str__() takes 1 positional argument but 2 were given`

This is due to the super \_\_str__ function using self as its argument which is not the self given as its argument from the Vlans class.
getattr(Record obj) is called instead of getattr(Vlans obj)

My proposed change would either be a revert of the commit or an addition where we hand over the Vlans object as an additional argument and calling getattr in the Record \_\_str__ class with the argument or itself. (geattr(arg or self,...)

**Comment by markkuleinio** [comment]
Thanks for taking the time to report this.
