### ISSUE TITLE
missing setuptools dependency

### ISSUE THREAD

**Issue by Nothing4You** [netbox-community/pynetbox#451]
pynetbox currently depends on setuptools being available, but it does not declare setuptools as runtime dependency:

https://github.com/netbox-community/pynetbox/blob/944a44761650b0e3d1791ef0180e1dcb79877b4b/pynetbox/__init__.py#L1

`pkg_resources` is provided by setuptools.

I see 3 ways to solve this:
1. wrap in `try` block, catching `ImportError`
2. add explicit setuptools dependency
3. migrate to importlib alternatives as recommended in https://setuptools.pypa.io/en/latest/pkg_resources.html, this can be combined with 1 or 2 (for backported implementations) on older python versions.

**Comment by abhi1693** [comment]
This will be superseded by #564 when thats merged
