### ISSUE TITLE
accessing objects in recordset fails

### ISSUE THREAD

**Issue by flynn1973** [netbox-community/pynetbox#454]
sorry, but i am out of ideas...skimmed all the docs and issues but nothing....
i need to access the prefix by its object name in the recordset returned by the all method and get the id of the associated vrf .

````
pfx = nb.ipam.prefixes.all()
print(pfx['10.111.240.0/22'].vrf.id)
````
````
root@nimvie: /home/tremch/scripts # ./netbox_import.py
Traceback (most recent call last):
  File "./netbox_import.py", line 80, in <module>
    x = pfx['10.111.240.0/22']
TypeError: 'RecordSet' object is not subscriptable
````
allso tried numerous variations of this...did not work out
````
pfx = nb.ipam.prefixes.all()
#pfx = list(pfx)
#print(pfx['10.111.240.0/22'].vrf.id)
#x = pfx['10.111.240.0/22']
#print(x.vrf.id)

````
how is this supposed to work?

**Comment by markkuleinio** [comment]
`.all()` returns the RecordSet (which is almost like a list) that you can iterate over, like this:

```
prefixes = nb.ipam.prefixes.all()
for pfx in prefixes:
    if pfx.prefix == "10.111.240.0/22":
        print(pfx.prefix, pfx.vrf.id)
```

If you need to iterate over the same `prefixes` many times, then you can first convert the RecordSet to list: `prefixes = list(nb.ipam.prefixes.all())`.

If you want to index over the results (like you tried), then you need to first create your own dict:

```
prefixes = {}
for pfx in nb.ipam.prefixes.all():
    prefixes[pfx.prefix] = pfx

print(prefixes["10.111.240.0/22"].vrf.id)
print(prefixes["10.222.240.0/22"].vrf.id)
```

**Comment by flynn1973** [comment]
ah, thank you...helped a lot
