### ISSUE TITLE
Filter by custom fields that have hyphen in the name

### ISSUE THREAD

**Issue by lamoni** [netbox-community/pynetbox#458]
Hello all, hopefully I'm missing something obvious (probably am)

Is there a way to filter by custom fields that have hyphen in the name?

E.g. this obviously won't work in Python:

devices = nb.dcim.devices.filter(cf_testing-name-with-hyphen="some value")

Now my mind thinks that replacing - with _ should possibly work, but then I wonder if we have to worry about ambiguity  (because testing_something and testing-something can both exist as custom fields I think? Obviously having two custom fields named like that would be terrible practice, but it's not technically against the system's rules, so the ambiguity exists if we were to auto-magic replace the underscores with hyphens, regardless)

Is it possible to pass a payload or something instead of doing the auto-magic parameter way so I can very strictly define the filter I am after?

**Comment by jeremystretch** [comment]
Python variables can't have hyphens in them. You can work around this by passing a dictionary of keyword arguments, but in general its best to use underscores in custom fields names instead:

```
devices = nb.dcim.devices.filter(**{"cf_testing-name-with-hyphen": "some value"})
```
