### ISSUE TITLE
Is Pynetbox compatible with latest version of Netbox docker (3.2.1) ?

### ISSUE THREAD

**Issue by aconte31** [netbox-community/pynetbox#462]
Hello,

I would like to know if pynetbox is working with the last update of Netbox-docker 3.2.1. Because I updated my Netbox ans reinstalled pynetbox on it. But it doesn't found the module anymore.

```
File "/tmp/ansible_netbox_tenant_payload_tue5b_ed/ansible_netbox_tenant_payload.zip/ansible_collections/netbox/netbox/plugins/module_utils/netbox_utils.py", line 25, in <module>
    import pynetbox
ModuleNotFoundError: No module named 'pynetbox'
```

If someone has an idea.

Best regards.

**Comment by kaon1** [comment]
@aconte31 I'm seeing a similar error. What was your fix?
