### ISSUE TITLE
Bulk update not working

### ISSUE THREAD

**Issue by allan-silverstein** [netbox-community/pynetbox#464]
I'm trying to do a simple bulk update of a field in racks.  I'm following the documentation but it is hitting a ValueError (line 358 endpoint.py).  The documentation in the method gives the below example.

```
        Use bulk update by passing a list of Records:

        >>> devices = nb.dcim.devices.all()
        >>> for d in devices:
        >>>     d.name = d.name+'-test'
        >>> nb.dcim.devices.update(devices)
        >>> True
```

I'm trying to do pretty much the same exact thing...

```
nb_rack_recordset = nb.dcim.racks.all()
for rack in nb_rack_recordset:
    rack.custom_fields['dri_reservable'] = False

nb.dcim.racks.update(nb_rack_recordset)
```

Running a small script yields this error:

```
Traceback (most recent call last):
  File "/home/asilver/pyprojects/aoe-lab-network-mgmt/dri_netbox/netbox_bulk_update_fail.py", line 24, in <module>
    nb.dcim.racks.update(nb_rack_recordset)
  File "/home/asilver/pyvenv/conf_bkups/lib/python3.10/site-packages/pynetbox/core/endpoint.py", line 358, in update
    "Objects passed must be list[dict|Record] - was " + type(objects)
TypeError: can only concatenate str (not "type") to str
```

It appears this method wants to be passed a list object and not a recordset object.  Any suggestion how to do the bulk update?  Note, I can successful update a single rack record object using the save() method but I would really like to use the bulk update.  Note, I don't think the example in the documentation would work either as nb.dcim.devices.all() also returns a recordset....
Thank you.

**Comment by Bapths** [comment]
Hi!

I'm also facing issues with update. By following the documentation, the following code should just update the name of device 1 and 2:
```python
from pynetbox import api

test = api(url='url', token='token')

test.dcim.devices.update(
    [
        {'id': 1, 'name': 'rename-test1'},
        {'id': 2, 'name': 'rename-test2'}
    ]
)
```

But I get the following error instead:
```
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'non_field_errors': ['Expected a list of items but got type "dict".']}
```

I really don't understand why and what I am doing wrong. I am using
```
certifi==2022.5.18.1
charset-normalizer==2.0.12
idna==3.3
pynetbox==6.6.2
requests==2.27.1
six==1.16.0
urllib3==1.26.9
```
with Netbox 3.1.9.

**Comment by markkuleinio** [comment]
Looks like the documentation was not updated when the RecordSet results were introduced.

@allan-silverstein Use `devices = list(nb.dcim.devices.all())` (ie. change the RecordSet generator to a list of Records)

@Bapths Works here with `pynetbox` 6.6.2 and NetBox 3.2.1:

```
>>> netbox.dcim.devices.get(1).name
'Test'
>>> netbox.dcim.devices.get(2).name
'Test2'
>>> netbox.dcim.devices.update([{"id": 1, "name": "NewTest"}, {"id": 2, "name": "NewTest2"}])
[NewTest, NewTest2]
>>> netbox.dcim.devices.get(1).name
'NewTest'
>>> netbox.dcim.devices.get(2).name
'NewTest2'
>>>
```

**Comment by allan-silverstein** [comment]
Changing to a list fixed it.... Thank you
