### ISSUE TITLE
Error when trying to use update() on endpoint

### ISSUE THREAD

**Issue by Bapths** [netbox-community/pynetbox#466]
### Versions:
- Python **3.9**
- Netbox **3.2.4**
- Pynetbox **6.6.2**

### My code (following almost exactly the documentation):
```python
from pynetbox import api

nb = api(
    'https://netbox.local',
    token='******************************************'
)

test = nb.dcim.devices.update([
    {'id': 1, 'name': 'test'}
])
```

### What I expected:
The device with id 1 should be renamed 'test'.

### What I actually get:
```
Traceback (most recent call last):
  File "/Users/bapth/PyCharm/test-env/nb-test.py", line 8, in <module>
    test = nb.dcim.devices.update([
  File "/Users/bapth/PyCharm/test-env/.env/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 374, in update
    req = Request(
  File "/Users/bapth/PyCharm/test-env/.env/lib/python3.9/site-packages/pynetbox/core/query.py", line 427, in patch
    return self._make_call(verb="patch", data=data)
  File "/Users/bapth/PyCharm/test-env/.env/lib/python3.9/site-packages/pynetbox/core/query.py", line 287, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'non_field_errors': ['Expected a list of items but got type "dict".']}
```

### Comments
I get this error since I both updated Netbox and pynetbox. Since my code is using the update function it no longer works. I don't know if this could change anything but I'm using an Apple M1 chip.
I have also tried to update with a list of Record object but it does not work either:
```python
from pynetbox import api

nb = api(
    'https://netbox.local',
    token='******************************************'
)

devices = nb.dcim.devices.all()
for d in devices:
    d.name = d.name + '-test'

test = nb.dcim.devices.update(devices)
```

**Comment by markkuleinio** [comment]
As mentioned in https://github.com/netbox-community/pynetbox/issues/464#issuecomment-1132918795, the `.all()` method does not return a list but a generator, so you need to convert it to a list if you want to use it more than once.

And, in that same post I mentioned that the code to update two devices at the same call was working for me.

Please try again without `pynetbox`: use direct API calls with curl or similar tool to find out where your problem is.

**Comment by Bapths** [comment]
> As mentioned in https://github.com/netbox-community/pynetbox/issues/464#issuecomment-1132918795, the `.all()` method does not return a list but a generator, so you need to convert it to a list if you want to use it more than once.
> 
> 
> 
> And, in that same post I mentioned that the code to update two devices at the same call was working for me.
> 
> 
> 
> Please try again without `pynetbox`: use direct API calls with curl or similar tool to find out where your problem is.

Hi! Thank you for your quick answer.

I understand that the ".all()" method returns a generator and not a list but I just used the example in the documentation, so there may be errors in the documentation?

For the second part, did you try with the last version of Netbox? Because it is working for me with older versions but not the latest ones. I managed to do what I want without using Pynetbox, but the whole point was to use pynetbox to make usage of the API easyer... I even tried to reinstall my whole Netbox and try my script with a new linux VM but I still get this issue.

**Comment by markkuleinio** [comment]
> so there may be errors in the documentation?

Yeah, who knew

(https://github.com/netbox-community/pynetbox/pull/467 submitted)

> did you try with the last version of Netbox?

```
>>> pynetbox.__version__
'6.6.2'
>>> nb.status()["netbox-version"]
'3.2.4'
>>> devices = nb.dcim.devices.update([
...     {'id': 1, 'name': 'Yes#1'},
...     {'id': 2, 'name': 'Tested#2'},
... ])
>>> devices
[Yes#1, Tested#2]
>>>
```

> the whole point was to use pynetbox to make usage of the API easyer

Before solving a problem in `pynetbox` code it must be established that the problem is in fact in `pynetbox`, thus testing with direct API calls is a valid request, especially when it has already been shown by other members of community that `pynetbox` worked for them.

**Comment by markkuleinio** [comment]
Do you have any custom fields for devices?

**Comment by Bapths** [comment]
Hi! I have some clues on the origin of my issue.

> Do you have any custom fields for devices?

No, no custom fields are used.

> Before solving a problem in pynetbox code it must be established that the problem is in fact in pynetbox, thus testing with direct API calls is a valid request, especially when it has already been shown by other members of community that pynetbox worked for them.

I'm a able to perform PATCH requests **BUT** I found a slight change that might be the issue:

When performing a PATCH request on /dcim/devices/ with the following data
```json
{
  "id": 1,
  "name": "rename_test"
}
```
I get an Error 400 Bad Request
```json
{
  "non_field_errors": [
    "Expected a list of items but got type \"dict\"."
  ]
}
```
This is the same error I get when using pynetbox. But if I just add `[` `]` to my data
```json
[
  {
    "id": 1,
    "name": "rename_test"
  }
]
```
Then it is working fine. So I assume pynetbox does not add these brackets... But now I can not to understand why it is working for you and not for me 🤔

**Comment by Bapths** [comment]
> Then it is working fine. So I assume pynetbox does not add these brackets... But now I can not to understand why it is working for you and not for me 🤔

Acutally it does add the brackets 🤔 I verified it by adding a `print(data)` in the query.py file
```Python
        ...
        if not url_override:
            if self.filters:
                params.update(self.filters)
            if add_params:
                params.update(add_params)
        print(data)  # Added line 
        req = getattr(self.http_session, verb)(
            url_override or self.url, headers=headers, params=params, json=data
        )

        if req.status_code in [204, 409] and verb == "post":
            raise AllocationError(req)
        ...
```
I do get `[{'id': 1, 'name': 'test'}]` in my terminal before raising the error. So I do not really understand where the issue come from 😔

**Comment by Bapths** [comment]
I finally found where was my mistake. I did not specify the port of my netbox server when using the api object.
By just replacing
```Python
nb = api(
    url='https://netbox.local',
    token='my-token'
)
```
with
```Python
nb = api(
    url='https://netbox.local:443',
    token='my-token'
)
```
it all works just fine... Sorry for the useless issue report and thank you again for your kick answer.
