### ISSUE TITLE
Identify parent prefix of an IP address object.

### ISSUE THREAD

**Issue by agreusel** [netbox-community/pynetbox#469]
I have a use case where a particular IP address is allocated from a prefix in NetBox. I can query the IP address object via the API using pynetbox, but there isn't any relational data in the IP address object to point back to the parent prefix. I found a solution using the straight NetBox API to query prefixes containing the IP address (https://netbox/api/ipam/prefixes/?contains=10.0.0.1), which I can, through mask length logic, determine the actual parent. I'm trying to figure out if pynetbox itself has a mechanism to identify the parent prefix, or at least replicate the direct API query with a resulting list of prefixes I can act on.

If you look at the IP address details page in the NetBox UI, it clearly is natively building the parent prefix relationship somehow.

Any help would be appreciated!

**Comment by markkuleinio** [comment]
In general `pynetbox` does not care about the API call arguments, so everything is passed to the NetBox API:

```
>>> list(netbox.ipam.prefixes.filter(contains="10.120.1.1"))
[10.120.0.0/14, 10.120.1.0/24]
>>>
```

**Comment by agreusel** [comment]
This worked like a charm. Much appreciated!
