### ISSUE TITLE
.all() needs to be called more than once

### ISSUE THREAD

**Issue by Beinish** [netbox-community/pynetbox#484]
I'm trying to map my switches to their corresponding device in Netbox.

I have a list of switches for example: `[US-switch01, US-switch02]`
If those devices don't exist in Netbox, I would like to create that device. Here is the script right now:

```python
import pynetbox
nb = pynetbox.api(
    'http://netbox.domain.com',
    token='token'
)

devices = nb.dcim.devices.all()
sites = nb.dcim.sites.all()

def getSiteID(site):
    for s in sites:
        if s.name.upper() == site.upper():
            return s.id

def getDeviceID(device):
    for d in devices:
        if d.name.upper() == device.upper():
            return d.id

if __name__ == "__main__":
    switch_list = ["US-switch01", "US-switch02"]
    for switch in switch_list:
        print(f"Working on {switch}")
        if getDeviceID(switch) is None:
            siteName = switch.split('-')[0]
            print(siteName, getSiteID(siteName))
```

When I run my script, I first test what it would find:
```python
print(siteName, getSite(siteName))
```
So the above print should return `siteName` and the Side ID, which is what `getSite()` is doing.
The expected output is:
```
Working on US-switch01
US 1 #site name is US and the ID in netbox is 1
Working on US-switch02
EU 2 #site name is US and the ID in netbox is 1
```
For some reason, the output is this:
```
Working on US-switch01
US 1
Working on US-switch02
US None
```
Why do I get `None` as the returned value on the 2nd loop?

## The weird part

If I use this list: `[US-switch01, EU-switch01]` then the script works:
```
Working on US-switch01
US 1
Working on EU-switch02
EU 2
```

So the issue seems to be when there are 2 consecutive switches with the same site. Why? What am I missing here?

To "fix" this. I need to run call this again:
```python
devices = nb.dcim.devices.all()
sites = nb.dcim.sites.all()
```
Then it would work, but it seems wrong to call the same thing twice.

**Comment by markkuleinio** [comment]
See https://github.com/netbox-community/pynetbox/pull/476/files

**Comment by Beinish** [comment]
Thank you very much, that did the trick!
