### ISSUE TITLE
Feature request: API token expire time

### ISSUE THREAD

**Issue by yixiuGit** [netbox-community/pynetbox#486]
Is it possible to add one more parameter when call "create_token" method to specify the duration of the new token?
Every time same user login, they just need to enter their userID and pw, new token will be created and used, after certain time saying 1 hour, token will automatically expired and user need to login again

**Comment by abhi1693** [comment]
This is a limitation on NetBox API that it only takes username and password and generate a token for it.

**Comment by abhi1693** [comment]
I'd suggest to open an issue on [netbox](https://github.com/netbox-community/netbox/issues/new/choose) to enable additional parameters for token provisioning.
