### ISSUE TITLE
unable to create journal-entries

### ISSUE THREAD

**Issue by sebastiaanvduijn** [netbox-community/pynetbox#495]
Error while calling the create journal entries api:

Traceback (most recent call last):
  File "/etc/freeradius/3.0/mods-config/python3/test1.py", line 12, in <module>
    test = nb.extras.journal-entries.all()
NameError: name 'entries' is not defined

Same for create and get

**Comment by markkuleinio** [comment]
https://pynetbox.readthedocs.io/en/latest/endpoint.html:

> In order to call NetBox endpoints with dashes in their names you should convert the dash to an underscore. (E.g. querying the ip-addresses endpoint is done with nb.ipam.ip_addresses.all().)

```
>>> nb.extras.journal_entries.all()
<pynetbox.core.response.RecordSet object at 0x7f7b10b27550>
>>> list(nb.extras.journal_entries.all())
[2022-04-05 16:45 (Info)]
>>>
```

**Comment by arthanson** [comment]
Closing.  @markkuleinio identified the issue.
