### ISSUE TITLE
Rename model dcim.ConnectedEndpoint to dcim.ConnectedEndpoints and it conform to the new cable termination model from 3.3.x

### ISSUE THREAD

**Issue by ChilloManiac** [netbox-community/pynetbox#517]
In netbox 3.3.x cables support multiple terminations on either end - The corresponding model of e.g. an interface uses `connected_endpoints` now instead of `connected_endpoint` and contains a list of interfaces.

Pynetbox version: 6.6.2

**Comment by arthanson** [comment]
Closing
