### ISSUE TITLE
Support for netbox-acls?

### ISSUE THREAD

**Issue by fansari** [netbox-community/pynetbox#532]
Does pynetbox support netbox-acls or is this planned?

https://github.com/ryanmerolle/netbox-acls

**Comment by arthanson** [comment]
Not currently.  pynetbox is designed to support the core NetBox and currently doesn't support plugins as this could cause a lot of maintainability issues.  Calling directly via the requests library would work.

**Comment by abhi1693** [comment]
@arthanson was the `Plugins` class removed recently?

**Comment by Kani999** [comment]
I believe you can access the plugin endpoint by:
`nb.plugins.<plugin_name>.<plugin_model>.<action (get, create, etc)>`

At least I use it like that but with version `6.6.2` right now.
