### ISSUE TITLE
String concatenation without type casting can cause `TypeError`  

### ISSUE THREAD

**Issue by nautics889** [netbox-community/pynetbox#538]
There are a couple of lines in `pynetbox/core/endpoint.py` module having string concatenation without type casting.
[Line 461](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L461):
```
            raise ValueError(
                "Objects passed must be list[dict|Record] - was " + type(objects)
            )
```
[Line 475](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L475):
```
                raise ValueError(
                    "Object passed must be dict|Record - was " + type(objects)
                )
```
This obviously can lead to `TypeError`:
```
>>> 'Some string  ' + type(something)
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.3.2\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
TypeError: can only concatenate str (not "type") to str
``` 
It should have explicit type casting via `str()` like, e. g. like at [this line](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L521).
___
As for me the most readable solution would be to use `.format()` (like [there](https://github.com/netbox-community/pynetbox/blob/master/pynetbox/core/endpoint.py#L590)).

**Comment by abhi1693** [comment]
Fixed with #539
