### ISSUE TITLE
Type Problems

### ISSUE THREAD

**Issue by Pedromdsn** [netbox-community/pynetbox#546]
I don't have access to pynetbox typings, when I try to access a device it says that the function always returns null.
Although it worked I believe it was a good addition.

![image](https://user-images.githubusercontent.com/57453260/234595390-f384896b-7ee1-4a92-be65-c277e8a33400.png)

![image](https://user-images.githubusercontent.com/57453260/234596462-0e5decad-b9fe-42d2-bda8-c51442b6326e.png)

**Comment by abhi1693** [comment]
Try this because the `.get()` does not know what `1` means without its identifier

```python
device = nb.dcim.device.get(id=1)
print(device.name)
```

Note the above will only work if a device with ID=1 exists, otherwise you will get `None`

**Comment by Pedromdsn** [comment]
> Try this because the `.get()` does not know what `1` means without its identifier
> 
> ```python
> device = nb.dcim.device.get(id=1)
> print(device.name)
> ```
> 
> Note the above will only work if a device with ID=1 exists, otherwise you will get `None` and print will throw an error.

Even so, just understand as Nome, doesn't give me the typing.
![image](https://user-images.githubusercontent.com/57453260/235693065-e686630e-7d0a-4fdb-aa16-6683f0254db5.png)

**Comment by abhi1693** [comment]
This library does not have any typings. It depends on the API schema that NetBox provides.

**Comment by Pedromdsn** [comment]
> This library does not have any typings. It depends on the API schema that NetBox provides.

Wouldn't it be possible to add typing?
Not even putting an object type.
The code works but I keep getting an error in VSCode
