### ISSUE TITLE
Add classifier and testing for Python 3.12

### ISSUE THREAD

**Issue by markkuleinio** [netbox-community/pynetbox#600]
### pynetbox version

v7.3.0

### NetBox version

v3.7.0

### Feature type

Change to existing functionality

### Proposed functionality

Add Python 3.12 in setup.py classifiers and in the test runs.

### Use case

Python 3.12 has been out for three months, and the first fix release 3.12.1 is also out already, so let's test against it as well.

**Comment by abhi1693** [comment]
@markkuleinio Would you like to submit a PR?

**Comment by markkuleinio** [comment]
That'll be tomorrow (EET) but yes

**Comment by arthanson** [comment]
Closed, update to support Python 3.12
