### ISSUE TITLE
`vpn` endpoint not available for Netbox 4

### ISSUE THREAD

**Issue by LDTips** [netbox-community/pynetbox#638]
### pynetbox version

7.4.0

### NetBox version

4.0.9

### Python version

3.11

### Steps to Reproduce

Simply create netbox api handle and try invoking vpn endpoint object
For Netbox 3.7 at Python 3.10
```
nb = pynetbox.api(NETBOX3_ADDRESS, token=TOKEN, threading=True)
nb.version
'3.7'
nb.vpn
<pynetbox.core.app.App object at 0x7f4bb1b58070>
```
Meanwhile for Netbox 4, tested on Python 3.11
```
nb = pynetbox.api(NETBOX4_ADDRESS, token=TOKEN, threading=True)
nb.version
'4.0'
nb.vpn
Traceback (most recent call last):
  File "C:\ptc\JetBrains\PycharmPro\plugins\python\helpers\pydev\pydevconsole.py", line 364, in runcode
    coro = func()
           ^^^^^^
 ```
 

### Expected Behavior

I expected `vpn` object to be available for Netbox 4

### Observed Behavior

`vpn` object is not available for Netbox 4

**Comment by arthanson** [comment]
closing
