### ISSUE TITLE
Add support for NetBox Branching

### ISSUE THREAD

**Issue by mrmrcoleman** [netbox-community/pynetbox#642]
### pynetbox version

v7.4.0

### NetBox version

v4.1

### Feature type

Data model extension

### Proposed functionality

NetBox Branching adds branching capabilties to NetBox and was just moved to GA: https://github.com/netboxlabs/netbox-branching/releases/tag/v0.4.0

The branching API is split across two main end points:

1. api/plugins/branching/branches/

pynetbox users should be able read (and filter on), create, modify, sync, merge, revert and and delete branches

2. api/plugins/branching/changes/

pynetbox users should be able to query and filter on changes

### Use case

From the netbox-branching repo:

> This plugin introduces branching functionality. A branch is a discrete, static snapshot of the NetBox database which can be modified independently and later merged back into the main database. This enables users to make "offline" changes to objects within NetBox and avoid interfering with its integrity as the network source of truth. It also provides the opportunity to review changes in bulk prior to their application.

### External dependencies

NetBox 4.1
NetBox Branching

**Comment by arthanson** [comment]
Actually you can do it in the current version by setting `nb.http_session.headers["X-NetBox-Branch"]` to the schema_id of the branch:

```
import pynetbox


nb = pynetbox.api(
    'http://localhost:8000/',
    token='92e786e2344c7f6eded06309a75d2deef595f2bc'
)

num_sites = len(nb.dcim.sites.all())
print(f"number sites main branch: {num_sites}")

# switch to Branch 'a'
branch = nb.plugins.branching.branches.get(name='a')
nb.http_session.headers["X-NetBox-Branch"] = branch.schema_id

num_sites = len(nb.dcim.sites.all())
print(f"number sites a branch: {num_sites}")
```
